### ISSUE TITLE
tap-oracle not working with transformations (transform-field)

### ISSUE THREAD

**Issue by mpcarter** [transferwise/pipelinewise-tap-oracle#1]
See original issue posted by @johnoscott
https://github.com/transferwise/pipelinewise-transform-field/issues/9

Problem seems to be related to bad ACTIVATE_VERSION messages being sent by tap-oracle. Looks like it is passing the name of the table to the stream name instead of the tap_stream_id (which is typically in form of SCHEMA-TABLENAME). 

This debug output was shortened to remove irrelevant info...
```
time=2020-05-03 03:25:42 logger_name=transform_field log_level=DEBUG message={'type': 'SCHEMA', 'stream': 'RATERADMIN-AGENCY', 'schema': {'properties':  ...  'key_properties': ['ID']}
time=2020-05-03 03:25:42 logger_name=transform_field log_level=DEBUG message=Timings: unspecified: 0.000; validating: 0.000; transforming: 0.000;
time=2020-05-03 03:25:42 logger_name=transform_field log_level=DEBUG message={'type': 'STATE', 'value': {'bookmarks': {'RATERADMIN-AGENCY': {'last_replication_method': 'FULL_TABLE', 'version': 1588476342846}}, 'currently_syncing': 'RATERADMIN-AGENCY'}}
time=2020-05-03 03:25:42 logger_name=transform_field log_level=DEBUG message={'type': 'ACTIVATE_VERSION', 'stream': 'AGENCY', 'version': 1588476342846}
INFO select SELECT  ...
                                FROM RATERADMIN.AGENCY
                               ORDER BY ORA_ROWSCN ASC
time=2020-05-03 03:25:43 logger_name=transform_field log_level=DEBUG message={'type': 'RECORD', 'stream': 'RATERADMIN-AGENCY', 'record': ... 'version': 1588476342846, 'time_extracted': '2020-05-03T03:25:42.846005Z'}
time=2020-05-03 03:25:43 logger_name=transform_field log_level=CRITICAL message='AGENCY'
Traceback (most recent call last):
  File "/app/.virtualenvs/transform-field/bin/transform-field", line 8, in <module>
    sys.exit(main())
  File "/app/.virtualenvs/transform-field/lib/python3.7/site-packages/transform_field/__init__.py", line 223, in main
    raise exc
  File "/app/.virtualenvs/transform-field/lib/python3.7/site-packages/transform_field/__init__.py", line 215, in main
    main_impl()
  File "/app/.virtualenvs/transform-field/lib/python3.7/site-packages/transform_field/__init__.py", line 209, in main_impl
    TransformField(trans_config).consume(reader)
  File "/app/.virtualenvs/transform-field/lib/python3.7/site-packages/transform_field/__init__.py", line 201, in consume
    self.handle_line(line)
  File "/app/.virtualenvs/transform-field/lib/python3.7/site-packages/transform_field/__init__.py", line 180, in handle_line
    self.flush()
  File "/app/.virtualenvs/transform-field/lib/python3.7/site-packages/transform_field/__init__.py", line 91, in flush
    stream_meta = self.stream_meta[stream]
KeyError: 'AGENCY'
```

Since other taps seem to play nice with transform-field (e.g. tap-mysql) it seems this is most likely tap-oracle that needs a fix.

**Comment by koszti** [comment]
fixed by https://github.com/transferwise/pipelinewise-tap-oracle/pull/2

**Comment by johnoscott** [comment]
awesome !
