### ISSUE TITLE
libclntsh.so: cannot open shared object file: No such file or directory". See https://oracle.github.io/odpi/doc/installation.html#linux for help

### ISSUE THREAD

**Issue by visch** [transferwise/pipelinewise-tap-oracle#7]
Looks like there's a needed dependency on your machine before running this. I don't see it documented anywhere, maybe I"m missing something. 

CRITICAL DPI-1047: 64-bit Oracle Client library cannot be loaded: "libclntsh.so: cannot open shared object file: No such file or directory". See https://oracle.github.io/odpi/doc/installation.html#linux for help
Traceback (most recent call last):
  File "/home/visch/git/oracle2mssql/oracle2mssql/.meltano/extractors/tap-oracle/venv/bin/tap-oracle", line 8, in <module>
    sys.exit(main())
  File "/home/visch/git/oracle2mssql/oracle2mssql/.meltano/extractors/tap-oracle/venv/lib/python3.8/site-packages/tap_oracle/__init__.py", line 565, in main
    raise exc
  File "/home/visch/git/oracle2mssql/oracle2mssql/.meltano/extractors/tap-oracle/venv/lib/python3.8/site-packages/tap_oracle/__init__.py", line 562, in main
    main_impl()
  File "/home/visch/git/oracle2mssql/oracle2mssql/.meltano/extractors/tap-oracle/venv/lib/python3.8/site-packages/tap_oracle/__init__.py", line 552, in main_impl
    do_discovery(conn_config, filter_schemas)
  File "/home/visch/git/oracle2mssql/oracle2mssql/.meltano/extractors/tap-oracle/venv/lib/python3.8/site-packages/tap_oracle/__init__.py", line 301, in do_discovery
    connection = orc_db.open_connection(conn_config)
  File "/home/visch/git/oracle2mssql/oracle2mssql/.meltano/extractors/tap-oracle/venv/lib/python3.8/site-packages/tap_oracle/db.py", line 14, in open_connection
    conn = cx_Oracle.connect(config["user"], config["password"], make_dsn(config))
cx_Oracle.DatabaseError: DPI-1047: 64-bit Oracle Client library cannot be loaded: "libclntsh.so: cannot open shared object file: No such file or directory". See https://oracle.github.io/odpi/doc/installation.html#linux for help

**Comment by visch** [comment]
Installing https://www.oracle.com/database/technologies/instant-client/linux-x86-64-downloads.html (Oracle Instant Package) RPM package worked
