### ISSUE TITLE
Table or View does not exist during discovery

### ISSUE THREAD

**Issue by visch** [transferwise/pipelinewise-tap-oracle#8]
**Describe the bug**
Table or View does not exist during discovery

**To Reproduce**
1. Run discovery

**Expected behavior**
Discovery to output a catalog

**Screenshots**
```
INFO fetching row counts
INFO fetching tables:
   SELECT owner, table_name
   FROM all_tables
   WHERE owner != 'SYS' []
INFO fetching views
INFO fetching column info
INFO fetching pk constraints
CRITICAL ORA-00942: table or view does not exist

Traceback (most recent call last):
  File "/home/visch/git/oracle2mssql/oracle2mssql/.meltano/extractors/tap-oracle/venv/bin/tap-oracle", line 8, in <module>
    sys.exit(main())
  File "/home/visch/git/oracle2mssql/oracle2mssql/.meltano/extractors/tap-oracle/venv/lib/python3.8/site-packages/tap_oracle/__init__.py", line 565, in main
    raise exc
  File "/home/visch/git/oracle2mssql/oracle2mssql/.meltano/extractors/tap-oracle/venv/lib/python3.8/site-packages/tap_oracle/__init__.py", line 562, in main
    main_impl()
  File "/home/visch/git/oracle2mssql/oracle2mssql/.meltano/extractors/tap-oracle/venv/lib/python3.8/site-packages/tap_oracle/__init__.py", line 552, in main_impl
    do_discovery(conn_config, filter_schemas)
  File "/home/visch/git/oracle2mssql/oracle2mssql/.meltano/extractors/tap-oracle/venv/lib/python3.8/site-packages/tap_oracle/__init__.py", line 346, in do_discovery
    catalog = discover_columns(connection, table_info, filter_schemas)
  File "/home/visch/git/oracle2mssql/oracle2mssql/.meltano/extractors/tap-oracle/venv/lib/python3.8/site-packages/tap_oracle/__init__.py", line 277, in discover_columns
    md = produce_column_metadata(connection,
  File "/home/visch/git/oracle2mssql/oracle2mssql/.meltano/extractors/tap-oracle/venv/lib/python3.8/site-packages/tap_oracle/__init__.py", line 200, in produce_column_metadata
    database_name = get_database_name(connection)
  File "/home/visch/git/oracle2mssql/oracle2mssql/.meltano/extractors/tap-oracle/venv/lib/python3.8/site-packages/tap_oracle/__init__.py", line 189, in get_database_name
    rows = cur.execute("SELECT name FROM v$database").fetchall()
cx_Oracle.DatabaseError: ORA-00942: table or view does not exist
```

**Your environment**
 - Version of tap: latest I think
 - Version of python 3.8.6

**Additional context**

Unsure what exactly is happening here, been trying to dive in deeper

**Comment by visch** [comment]
Not a bug. Access issue 

` grant select on v_$database to (nameofuser)`

fixed this
