### ISSUE TITLE
Discovery generates a catalog that doesn't match the data

### ISSUE THREAD

**Issue by visch** [transferwise/pipelinewise-tap-oracle#9]
**Describe the bug**

jsonschema.exceptions.ValidationError: 66.666667 is not a multiple of 1e-06

Schema is wrong for the data that's there. 

target-csv      | Traceback (most recent call last):
target-csv      |   File "/home/visch/git/oracle2mssql/oracle2mssql/.meltano/loaders/target-csv/venv/bin/target-csv", line 8, in <module>
target-csv      |     sys.exit(main())
target-csv      |   File "/home/visch/git/oracle2mssql/oracle2mssql/.meltano/loaders/target-csv/venv/lib/python3.8/site-packages/target_csv.py", line 141, in main
target-csv      |     state = persist_messages(config.get('delimiter', ','),
target-csv      |   File "/home/visch/git/oracle2mssql/oracle2mssql/.meltano/loaders/target-csv/venv/lib/python3.8/site-packages/target_csv.py", line 59, in persist_messages
target-csv      |     validators[o['stream']].validate(o['record'])
target-csv      |   File "/home/visch/git/oracle2mssql/oracle2mssql/.meltano/loaders/target-csv/venv/lib/python3.8/site-packages/jsonschema/validators.py", line 130, in validate
target-csv      |     raise error
target-csv      | jsonschema.exceptions.ValidationError: 66.666667 is not a multiple of 1e-06
target-csv      |
target-csv      | Failed validating 'multipleOf' in schema['properties']['SCOREPERCENT']:
target-csv      |     {'exclusiveMaximum': True,
target-csv      |      'exclusiveMinimum': True,
target-csv      |      'maximum': 1000000000000,
target-csv      |      'minimum': -1000000000000,
target-csv      |      'multipleOf': 1e-06,
target-csv      |      'type': ['null', 'number']}
target-csv      |
target-csv      | On instance['SCOREPERCENT']:
target-csv      |     66.666667

**Your environment**
 - Version of tap: Latest
 - Version of python 3.8

**Comment by visch** [comment]
Not a bug with Oracle. The number is correct. target-csv issue / jsonschema issue.
